version: '3.8'

services:
    # techdinner-api:
    #     build: .
    #     image: techdinner-node
    #     container_name: techdinner-api
    #     networks:
    #         - techdinnernet

    # techdinner-nginx:
    #     image: nginx:alpine
    #     container_name: techdinner-nginx
    #     working_dir: /app
    #     volumes:
    #         - ./.nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    #     env_file:
    #         - .env
    #     ports:
    #         - 8585:80
    #     depends_on:
    #         - techdinner-api
    #     networks:
    #         - techdinnernet

    techdinner-db:
        image: postgres
        container_name: techdinner-db
        env_file:
            - .env
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}
        ports:
            - ${DB_PORT}:5432
        networks:
            - techdinnernet

networks:
  techdinnernet:
      driver: bridge
