version: '3.8'

services:
    node:
        build: .docker
        image: techdinner-node
        container_name: techdinner-api
        working_dir: /app
        expose:
            - 5000
        volumes:
            - ./:/app

    webserver:
        image: nginx:alpine
        container_name: techdinner-nginx
        working_dir: /app
        volumes:
            - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8585:80
        depends_on:
            - node

    mysql:
        image: mysql:5.7
        container_name: techdinner-db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: techdinner_db
            MYSQL_USER: techdinnerdb
            MYSQL_PASSWORD: techdinnerdb
        ports: 
            - 3306:3306