version: '3.8'

services:
    # node:
    #     build: .
    #     image: techdinner-node
    #     container_name: techdinner-api

    # webserver:
    #     image: nginx:alpine
    #     container_name: techdinner-nginx
    #     working_dir: /app
    #     volumes:
    #         - ./.nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    #     env_file:
    #         - .env
    #     ports:
    #         - ${APP_PORT}:80
    #     depends_on:
    #         - node

    mysql:
        image: mysql:5.7
        container_name: techdinner-db
        env_file:
            - .env
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASS}
        ports:
            - ${DB_PORT}:3306
