export default {
	clearMocks: true,
	collectCoverage: true,
	coverageDirectory: "coverage",
	coverageProvider: "v8",
	preset: "ts-jest",
	testEnvironment: "node",
	roots: ["<rootDir>/tests"],
	moduleNameMapper: {
		"@controllers/(.*)": "<rootDir>/src/app/controllers/$1",
		"@dtos/(.*)": "<rootDir>/src/app/dtos/$1",
		"@usecases/(.*)": "<rootDir>/src/domain/usecases/$1",
		"@builders/(.*)": "<rootDir>/src/app/builders/$1",
		"@config/(.*)": "<rootDir>/src/app/config/$1",
		"@decorators/(.*)": "<rootDir>/src/app/decorators/$1",
		"@factories/(.*)": "<rootDir>/src/app/factories/$1",
		"@interfaces/(.*)": "<rootDir>/src/app/interfaces/$1",
		"@middlewares/(.*)": "<rootDir>/src/app/middlewares/$1",
		"@repositories/(.*)": "<rootDir>/src/app/repositories/$1",
		"@server/(.*)": "<rootDir>/src/app/server/$1",
		"@services/(.*)": "<rootDir>/src/app/services/$1",
		"_config/(.*)": "<rootDir>/src/config/$1",
		"@database/(.*)": "<rootDir>/src/database$1",
		"@entities/(.*)": "<rootDir>/src/domain/entities/$1",
		"@infra/(.*)": "<rootDir>/src/infra/$1",
		"@routes/(.*)": "<rootDir>/src/routes/$1",
	},
};
